# Generated by Django 2.2.9 on 2020-08-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrases',
            name='user',
            field=models.IntegerField(),
        ),
    ]
