# Generated by Django 2.2.9 on 2020-08-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0002_auto_20200814_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrases',
            old_name='user',
            new_name='user_id',
        ),
    ]
