# Generated by Django 2.2.9 on 2020-08-14 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0003_auto_20200814_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrases',
            options={'ordering': ['user_id'], 'verbose_name': 'Phrase', 'verbose_name_plural': 'Phrases'},
        ),
        migrations.AddField(
            model_name='phrases',
            name='creted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
