# Generated by Django 2.2.9 on 2020-08-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0004_auto_20200814_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrases',
            old_name='creted',
            new_name='created',
        ),
    ]
